--SET MODE PostgreSQL;
--
--CREATE TABLE IF NOT EXISTS staff (
--  id int PRIMARY KEY auto_increment,
--  description VARCHAR,
--  completed BOOLEAN,
--  categoryid INTEGER
--);
--
--CREATE TABLE IF NOT EXISTS coarses (
--  id int PRIMARY KEY auto_increment,
--  name VARCHAR
--);

