--SET MODE PostgreSQL;
--
--CREATE TABLE IF NOT EXISTS employee (
--  id int PRIMARY KEY auto_increment,
--  description VARCHAR,
--  completed BOOLEAN,
--  categoryid INTEGER
--);
--
--CREATE TABLE IF NOT EXISTS departments (
--  id int PRIMARY KEY auto_increment,
--  name VARCHAR
--);

